
[tool.ruff]
target-version = "py311"
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "PLR", "PLW"]
ignore = [
  "E203",  # compatibility with formatter
  "E501",  # line length (handled in dev, not CI failure)
]
